export { default as worker } from './worker.png';
export { default as worker2 } from './worker2.png';
export { default as carpintero } from './carpintero.png';
export { default as cerrajero } from './cerrajero.png';
export { default as gasfitero } from './gasfitero.png';
export { default as paso1 } from './paso1.png';
export { default as paso2 } from './paso2.png';
export { default as paso3 } from './paso3.png';
export { default as LogoBN } from './LogoBN.png';